### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by usbalbin**
# v0.4.0

## Breaking
* #21 Update `FromIteratorFixed` trait to avoid unnameable iterator type as type paramater in the trait
  ```diff
  - pub trait FromIteratorFixed<I: Iterator, const N: usize> {
  -     fn from_iter_fixed(iter_fixed: IteratorFixed<I, N>) -> Self;
  + pub trait FromIteratorFixed<T, const N: usize> {
  +     fn from_iter_fixed<I: Iterator<Item = T>>(iter_fixed: IteratorFixed<I, N>) -> Self;
    }
  ```
## Other changes

* #22
* #20
* #24
* #25 

## Thank you
* @Daniel-Aaron-Bloom
* @gwen-lg

### CODE REVIEW

**Comment by gwen-lg** [comment]
perhaps list changes and the fact than can break use ?
In commit and PR descriptions ?

**Comment by gwen-lg** [comment]
Oh, I'm thinking about it.
Clippy also say "missing documentation for the crate"
from https://rust-lang.github.io/rust-clippy/master/index.html#missing_docs_in_private_items

Perhaps it could be good to have one, to have more information on [doc](https://docs.rs/iter_fixed/0.3.1/iter_fixed/).
But I was not sure about what to say and avoid copy past of Readme or part of it.

**Comment by Daniel-Aaron-Bloom** [comment]
I mean, you could copy the readme and use something like https://crates.io/crates/cargo-readme to make sure they don't get out of sync.

**Comment by usbalbin** [comment]
Perhaps there is a better way, but what about using cargo-readme to create a temporary file and something like [diff](https://github.com/marketplace/actions/smart-diff) to see if the committed README.md is up to date as part of the ci workflow?

**Comment by usbalbin** [comment]
Thank you both :)

**Pull request merged**
